/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ControlBar: typeof import('./src/components/ControlBar.vue')['default']
    ControlBtn: typeof import('./src/components/ControlBtn.vue')['default']
    IcRoundMessage: typeof import('./src/components/Icons/IcRoundMessage.vue')['default']
    MaterialSymbolsCancel: typeof import('./src/components/Icons/MaterialSymbolsCancel.vue')['default']
    MaterialSymbolsDeleteRounded: typeof import('./src/components/Icons/MaterialSymbolsDeleteRounded.vue')['default']
    MaterialSymbolsSyncRounded: typeof import('./src/components/Icons/MaterialSymbolsSyncRounded.vue')['default']
    MingcuteCloseFill: typeof import('./src/components/Icons/MingcuteCloseFill.vue')['default']
    MingcuteLockFill: typeof import('./src/components/Icons/MingcuteLockFill.vue')['default']
    MingcuteMinimizeFill: typeof import('./src/components/Icons/MingcuteMinimizeFill.vue')['default']
    MingcutePin2Fill: typeof import('./src/components/Icons/MingcutePin2Fill.vue')['default']
    MingcutePinFill: typeof import('./src/components/Icons/MingcutePinFill.vue')['default']
    MingcuteUnlockFill: typeof import('./src/components/Icons/MingcuteUnlockFill.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBadge: typeof import('naive-ui')['NBadge']
    NButton: typeof import('naive-ui')['NButton']
    NButtonGroup: typeof import('naive-ui')['NButtonGroup']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NGradientText: typeof import('naive-ui')['NGradientText']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NLayout: typeof import('naive-ui')['NLayout']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NPopover: typeof import('naive-ui')['NPopover']
    NProgress: typeof import('naive-ui')['NProgress']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NText: typeof import('naive-ui')['NText']
    NThing: typeof import('naive-ui')['NThing']
    RoomListItem: typeof import('./src/components/RoomListItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Updater: typeof import('./src/components/Updater.vue')['default']
    WinMenu: typeof import('./src/components/WinMenu.vue')['default']
  }
}
